DROP TABLE IF EXISTS UTILAISER;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS STORY;
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS IMAGES;
DROP TABLE IF EXISTS PROFILE;
DROP TABLE IF EXISTS VOTE;


CREATE TABLE UTILAISER
(
	username TEXT NOT NULL PRIMARY KEY,
	password VARCHAR(50) NOT NULL,
	email TEXT NOT NULL UNIQUE
);

CREATE TABLE POST
(
	postID TEXT PRIMARY KEY,
	username TEXT NOT NULL REFERENCES UTILAISER,
	description TEXT,
    postTime TEXT,
	vote INTEGER NOT NULL
);



CREATE TABLE COMMENT
(
    parentID TEXT REFERENCES POST,
    commentID TEXT REFERENCES POST,
    PRIMARY KEY(commentID)
);



CREATE TABLE IMAGES (
 imageID INTEGER PRIMARY KEY,
 file_name TEXT NOT NULL
);


CREATE TABLE STORY
(
    postID TEXT REFERENCES POST,
    title TEXT,
	imageID TEXT REFERENCES IMAGES,
    PRIMARY KEY(postID)
);

CREATE TABLE PROFILE (
 username TEXT NOT NULL REFERENCES UTILAISER,
 firstName TEXT NOT NULL,
 lastName TEXT NOT NULL,
 age INTEGER NOT NULL,
 imageID TEXT REFERENCES IMAGES,
 karma INTEGER NOT NULL,
 PRIMARY KEY(username)
);

CREATE TABLE VOTE
(
	username TEXT REFERENCES UTILAISER,
    postID TEXT REFERENCES POST,
	value INTEGER NOT NULL CHECK (value = 1 OR value = -1),
	PRIMARY KEY(username, postID)
);



