DROP TABLE IF EXISTS UTILAISER;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS STORY;
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS IMAGES;
DROP TABLE IF EXISTS PROFILE;

CREATE TABLE UTILAISER
(
	username TEXT NOT NULL PRIMARY KEY,
	password VARCHAR(50) NOT NULL,
	email TEXT NOT NULL UNIQUE
);

CREATE TABLE POST
(
	postID INTEGER PRIMARY KEY,
	username TEXT NOT NULL REFERENCES UTILAISER,
	description TEXT,
    postTime TIME,
	vote INTEGER NOT NULL
);

CREATE TABLE STORY
(
    postID INTEGER REFERENCES POST,
    title TEXT,
	imageID INTEGER REFERENCES IMAGES,
    PRIMARY KEY(postID)
);


CREATE TABLE COMMENT
(
    parentID INTEGER REFERENCES POST,
    commentID INTEGER REFERENCES POST,
    PRIMARY KEY(commentID)
);



CREATE TABLE IMAGES (
 imageID INTEGER PRIMARY KEY,
 file_name TEXT NOT NULL
);

CREATE TABLE PROFILE (
 username TEXT NOT NULL REFERENCES UTILAISER,
 firstName TEXT NOT NULL,
 lastName TEXT NOT NULL,
 age INTEGER NOT NULL,
 imageID INTEGER REFERENCES IMAGES,
 karma INTEGER NOT NULL,
 PRIMARY KEY(username)
);
