DROP TABLE IF EXISTS VOTECOMMENT;
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS VOTESTORY;
DROP TABLE IF EXISTS STORY;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
	userID INTEGER PRIMARY KEY,
	username TEXT NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL,
	email TEXT NOT NULL UNIQUE
);

CREATE TABLE POST
(
	postID INTEGER PRIMARY KEY
);

CREATE TABLE STORY
(
    postID INTEGER REFERENCES POST,
    title TEXT,
    description TEXT,
    PRIMARY KEY(postID)
);

CREATE TABLE VOTESTORY
(
	userID INTEGER REFERENCES USER,
	storyID INTEGER REFERENCES STORY,
	vote INTEGER NOT NULL Check (vote == -1 OR vote == 1),
	PRIMARY KEY(userID,storyID)
);


CREATE TABLE COMMENT
(
    userID INTEGER REFERENCES USER,
    postID INTEGER REFERENCES POST,
	description TEXT,
    postTime DATETIME,
    PRIMARY KEY(postTime,userID,postID)
)


CREATE TABLE VOTECOMMENT
(
	userID INTEGER REFERENCES USER,
	commentID INTEGER REFERENCES COMMENT,
	vote INTEGER NOT NULL Check (vote == -1 OR vote == 1),
	PRIMARY KEY(userID,commentID)
);


